CREATE PROCEDURE [dbo].[spAdmin_GetArchivedInternById]
	@Id int
AS
BEGIN
	SELECT 
		[Id],
		[FirstName], 
		[LastName], 
		[Department], 
		[DegreePlan], 
		[Role], 
		[StartDate], 
		[EndDate], 
		[DateCreated], 
		[DegreeConcentration], 
		[PersonalEmail], 
		[SchoolEmail], 
		[InternshipEmail], 
		[Track], 
		[InviteToMeetings], 
		[Email], 
		[EntranceSurvey], 
		[WelcomeDocument], 
		[ThreeSignedDocuments], 
		[ESETTraining], 
		[Resume], 
		[Orientation1Access], 
		[Orientation2Access], 
		[TCWAccess], 
		[PlannerAccess], 
		[TeamGroupChat], 
		[OneDriveSetup], 
		[AzureSetup], 
		[ExitSurveySent], 
		[Masterclass], 
		[InternNotes], 
		[LastUpdatedBy], 
		[LastUpdate]
	FROM
		ArchivedInterns
	WHERE
		Id = Id;
END