CREATE PROCEDURE [dbo].[spIntern_AddIntern]
	@FirstName nvarchar(50),
	@LastName nvarchar(50),
	@Department nvarchar(50),
	@DegreePlan nvarchar(100),
	@Role nvarchar(50),
	@StartDate date,
	@EndDate date,
	@DateCreated date,
	@DegreeConcentration nvarchar(50),
	@PersonalEmail nvarchar(100),
	@SchoolEmail nvarchar(100),
	@InternshipEmail nvarchar(100),
	@Track nvarchar(10),
	@InviteToMeetings bit,
	@Email bit,
	@EntranceSurvey bit,
	@WelcomeDocument bit,
	@ThreeSignedDocuments bit,
	@ESETTraining bit,
	@Resume bit,
	@Orientation1Access bit,
	@Orientation2Access bit,
	@TCWAccess bit,
	@PlannerAccess bit,
	@TeamGroupChat bit,
	@OneDriveSetup bit,
	@AzureSetup bit,
	@ExitSurveySent bit,
	@Masterclass bit,
	@InternNotes nvarchar(2000),
	@LastUpdatedBy nvarchar(150),
	@LastUpdate date
AS
BEGIN
	INSERT INTO Interns
	(
		FirstName,
		LastName,
		Department, 
		DegreePlan,
		[Role],
		StartDate,
		EndDate, 
		DateCreated,
		DegreeConcentration,
		PersonalEmail,
		SchoolEmail,
		InternshipEmail,
		Track,
		InviteToMeetings,
		Email,
		EntranceSurvey, 
		WelcomeDocument, 
		ThreeSignedDocuments,
		ESETTraining,
		[Resume],
		Orientation1Access,
		Orientation2Access,
		TCWAccess,
		PlannerAccess, 
		TeamGroupChat,
		OneDriveSetup, 
		AzureSetup, 
		ExitSurveySent,
		Masterclass,
		InternNotes, 
		LastUpdatedBy,
		LastUpdate
	)
	VALUES
	(
		@FirstName,
		@LastName,
		@Department, 
		@DegreePlan,
		@Role,
		@StartDate,
		@EndDate, 
		@DateCreated,
		@DegreeConcentration,
		@PersonalEmail,
		@SchoolEmail,
		@InternshipEmail,
		@Track,
		@InviteToMeetings,
		@Email,
		@EntranceSurvey, 
		@WelcomeDocument, 
		@ThreeSignedDocuments,
		@ESETTraining,
		@Resume,
		@Orientation1Access,
		@Orientation2Access,
		@TCWAccess,
		@PlannerAccess, 
		@TeamGroupChat,
		@OneDriveSetup, 
		@AzureSetup, 
		@ExitSurveySent,
		@Masterclass,
		@InternNotes, 
		@LastUpdatedBy,
		@LastUpdate
	);
	SELECT SCOPE_IDENTITY();
END

