CREATE PROCEDURE [dbo].[spIntern_EditIntern]
	@Id int,
	@FirstName nvarchar(50),
	@LastName nvarchar(50),
	@Department nvarchar(50),
	@DegreePlan nvarchar(50),
	@Role nvarchar(50),
	@StartDate date,
	@EndDate date,
	@DegreeConcentration nvarchar(50),
	@PersonalEmail nvarchar(100),
	@SchoolEmail nvarchar(100),
	@InternshipEmail nvarchar(100),
	@Track nvarchar(10),
	@InviteToMeetings bit,
	@Email bit,
	@EntranceSurvey bit,
	@WelcomeDocument bit,
	@ThreeSignedDocuments bit,
	@ESETTraining bit,
	@Resume bit,
	@Orientation1Access bit,
	@Orientation2Access bit,
	@TCWAccess bit,
	@PlannerAccess bit,
	@TeamGroupChat bit,
	@OneDriveSetup bit,
	@AzureSetup bit,
	@ExitSurveySent bit,
	@Masterclass bit,
	@InternNotes nvarchar(2000),
	@LastUpdatedBy nvarchar(150),
	@LastUpdate date

AS
BEGIN
	UPDATE Interns
	
	SET
		FirstName = @FirstName,
		LastName  = @LastName,
		Department = @Department,
		DegreePlan = @DegreePlan,
		[Role] = @Role,
		StartDate = @StartDate,
  		EndDate	= @EndDate,
		DegreeConcentration = @DegreeConcentration,
  		PersonalEmail = @PersonalEmail,
  		SchoolEmail = @SchoolEmail,
  		InternshipEmail = @InternshipEmail,
		Track = @Track,
  		InviteToMeetings = @InviteToMeetings,
		Email = @Email,
		EntranceSurvey = @EntranceSurvey,
		WelcomeDocument = @WelcomeDocument,
		ThreeSignedDocuments = @ThreeSignedDocuments,
		ESETTraining = @ESETTraining,
		[Resume] = @Resume,
		Orientation1Access = @Orientation1Access,
		Orientation2Access = @Orientation2Access,
		TCWAccess = @TCWAccess,
		PlannerAccess = @PlannerAccess,
		TeamGroupChat = @TeamGroupChat,
		OneDriveSetup = @OneDriveSetup,
		AzureSetup = @AzureSetup,
		ExitSurveySent = @ExitSurveySent,
		Masterclass = @Masterclass,
		InternNotes = @InternNotes,
		LastUpdatedBy = @LastUpdatedBy,
		LastUpdate = @LastUpdate
	WHERE
		Id = @Id;
END